2021-04-08T11:57:48-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 11:57:48" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usettest1 realm="" roles="" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT22673: Logout from 82.213.178.130 (session:00000000)"
2021-04-08T11:57:48-07:00 10.0.0.111 PulseSecure: 2021-04-08 11:57:48 - ive - [82.213.178.130] Default Network::usettest1()[] - Logout from 82.213.178.130 (session:00000000)
2021-04-08T11:58:04-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 11:58:04" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=userasdad realm="Users" roles="" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT24327: Primary authentication failed for userasdad/System Local from 82.213.178.130"
2021-04-08T11:58:04-07:00 10.0.0.111 PulseSecure: 2021-04-08 11:58:04 - ive - [82.213.178.130] Default Network::userasdad(Users)[] - Primary authentication failed for userasdad/System Local from 82.213.178.130
2021-04-08T11:58:04-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 11:58:04" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=userasdad realm="Users" roles="" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT23457: Login failed using auth server System Local (Local Authentication).  Reason: Failed"
2021-04-08T11:58:04-07:00 10.0.0.111 PulseSecure: 2021-04-08 11:58:04 - ive - [82.213.178.130] Default Network::userasdad(Users)[] - Login failed using auth server System Local (Local Authentication).  Reason: Failed
2021-04-08T11:58:14-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 11:58:14" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usettest1 realm="Users" roles="" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT24326: Primary authentication successful for usettest1/System Local from 82.213.178.130"
2021-04-08T11:58:14-07:00 10.0.0.111 PulseSecure: 2021-04-08 11:58:14 - ive - [82.213.178.130] Default Network::usettest1(Users)[] - Primary authentication successful for usettest1/System Local from 82.213.178.130
2021-04-08T11:58:14-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 11:58:14" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usettest1 realm="Users" roles="Users" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" duration= msg="AUT31504: Login succeeded for usettest1/Users (session:00000000) from 82.213.178.130 with Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0."
2021-04-08T11:58:14-07:00 10.0.0.111 PulseSecure: 2021-04-08 11:58:14 - ive - [82.213.178.130] Default Network::usettest1(Users)[Users] - Login succeeded for usettest1/Users (session:00000000) from 82.213.178.130 with Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0.
2021-04-08T11:58:15-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 11:58:15" pri=2 fw=10.0.0.9 vpn=ive ivs=Root user=System realm="" roles="" proto=auth src=127.0.0.1 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT31085: Number of concurrent users (2) exceeded the system limit (2)."
2021-04-08T11:58:15-07:00 10.0.0.111 PulseSecure: 2021-04-08 11:58:15 - ive - [127.0.0.1] Root::System()[] - Number of concurrent users (2) exceeded the system limit (2).
2021-04-08T12:08:35-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:08:35" pri=2 fw=10.0.0.9 vpn=ive ivs=Root user=System realm="" roles="" proto=auth src=127.0.0.1 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT31085: Number of concurrent users (2) exceeded the system limit (2)."
2021-04-08T12:08:35-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:08:35 - ive - [127.0.0.1] Root::System()[] - Number of concurrent users (2) exceeded the system limit (2).
2021-04-08T12:08:35-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:08:35 - ive - [127.0.0.1] Root::System()[] - Number of concurrent users (2) exceeded the system limit (2).
2021-04-08T12:12:32-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:12:32" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usettest1 realm="Users" roles="Users" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT22886: Session timed out for usettest1/Users (session:00000000) due to inactivity (last access at 11:58:14 2021/04/08). Idle session identified during routine system scan."
2021-04-08T12:12:32-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:12:32 - ive - [82.213.178.130] Default Network::usettest1(Users)[Users] - Session timed out for usettest1/Users (session:00000000) due to inactivity (last access at 11:58:14 2021/04/08). Idle session identified during routine system scan.
2021-04-08T12:14:18-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:14:18" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usertest2 realm="Users" roles="" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT24326: Primary authentication successful for usertest2/System Local from 82.213.178.130"
2021-04-08T12:14:18-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:14:18 - ive - [82.213.178.130] Default Network::usertest2(Users)[] - Primary authentication successful for usertest2/System Local from 82.213.178.130
2021-04-08T12:14:18-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:14:18" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usertest2 realm="Users" roles="Users" proto=auth src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" duration= msg="AUT31504: Login succeeded for usertest2/Users (session:00000000) from 82.213.178.130 with Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0."
2021-04-08T12:14:18-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:14:18 - ive - [82.213.178.130] Default Network::usertest2(Users)[Users] - Login succeeded for usertest2/Users (session:00000000) from 82.213.178.130 with Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0.
2021-04-08T12:14:20-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:14:20" pri=2 fw=10.0.0.9 vpn=ive ivs=Root user=System realm="" roles="" proto=auth src=127.0.0.1 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="AUT31085: Number of concurrent users (2) exceeded the system limit (2)."
2021-04-08T12:14:20-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:14:20 - ive - [127.0.0.1] Root::System()[] - Number of concurrent users (2) exceeded the system limit (2).
2021-04-08T12:14:39-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:14:39" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usertest2 realm="Users" roles="Users" proto= src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="USR24630: Password change failed for user usertest2/System Local. Reason : 'La contraseña anterior no es correcta'."
2021-04-08T12:14:39-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:14:39 - ive - [82.213.178.130] Default Network::usertest2(Users)[Users] - Password change failed for user usertest2/System Local. Reason : 'La contraseña anterior no es correcta'.
2021-04-08T12:14:54-07:00 10.0.0.111 PulseSecure: id=firewall time="2021-04-08 12:14:54" pri=6 fw=10.0.0.9 vpn=ive ivs=Default Network user=usertest2 realm="Users" roles="Users" proto= src=82.213.178.130 dst= dstname= type=vpn op= arg="" result= sent= rcvd= agent="" duration= msg="USR22898: User Accounts modified. Changed password for username usertest2."
2021-04-08T12:14:54-07:00 10.0.0.111 PulseSecure: 2021-04-08 12:14:54 - ive - [82.213.178.130] Default Network::usertest2(Users)[Users] - User Accounts modified. Changed password for username usertest2.